# argparse
add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/argparse")

# sourcepp
set(SOURCEPP_LIBS_START_ENABLED OFF CACHE INTERNAL "" FORCE)
set(SOURCEPP_USE_BSPPP           ON CACHE INTERNAL "" FORCE)
set(SOURCEPP_USE_STEAMPP         ON CACHE INTERNAL "" FORCE)
set(SOURCEPP_USE_VPKPP           ON CACHE INTERNAL "" FORCE)
set(SOURCEPP_USE_VTFPP           ON CACHE INTERNAL "" FORCE)
add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/sourcepp")
